### ISSUE TITLE
TiddlyBlink is deprecated and replaced by Stroll

### ISSUE THREAD

**Issue by herbhuang** [joekroese/tiddlyroam#12]
Hi,

This is really a fantastic works and thank you for your efforts on this project.

I'd like to inform that [TiddlyBlink](https://giffmex.org/gifts/tiddlyblink.html) is now replace by its successor, [Stroll](https://giffmex.org/stroll/stroll.html). Hope this information could provide some information for your development of TiddlyRoam.

Best wishes .

**Comment by jokroese** [comment]
Thanks for the kind words @hwongbaul and thanks for sharing this news! I will have some time to develop TiddlyRoam further next week so I will look at Stroll and see if there is anything there that we should be incorporating.
