### ISSUE TITLE
[IDEA] Update to Stroll

### ISSUE THREAD

**Issue by kookma** [joekroese/tiddlyroam#20]
Hi @joekroese - Many thanks for this useful app and the great landing page. I am not sure if you have recently followed the Tiddlywiki forum! The Tiddlybilink which is used in Tiddlyroam has improved and now Stroll replaced it.

I would recommend to update Tiddlyream with latest Stroll.

**Comment by alexandergogl** [comment]
Good idea. However, the Stroll developer mentions Stroll having a lot of incompatibilities with TiddlyMap [here](https://giffmex.org/stroll/stroll.html#Troubleshooting).

**Comment by kookma** [comment]
> Good idea. However, the Stroll developer mentions Stroll having a lot of incompatibilities with TiddlyMap [here](https://giffmex.org/stroll/stroll.html#Troubleshooting).

Correct! but tiddlyblink is outdated tool!
