### ISSUE TITLE
Document TiddlyWiki compatibility

### ISSUE THREAD

**Issue by BrunoVernay** [joekroese/tiddlyroam#3]
If it is compatible with TiddlyWiki you should state explicitly that if this project stop, the data can be reused in a classical TD.
Also why isn't this project a TiddlyWiki plugin?  Because there are incompatibilities?
It is a documentation issue.

**Comment by jokroese** [comment]
For 1), feel free to make a pull request to add this to the documentation! It's not a priority for me but happy for someone else to do it.

For 2) TiddlyRoam is focused on being easy to use, particularly for people new to TiddlyWiki. I like that people can download a single html file and start using TiddlyRoam. TiddlyWiki plugins involve a multistep process and so aren't as fitting for the goal of TiddlyRoam.

That said, I'm more than happy for someone to port TiddlyRoam to a TiddlyWiki plugin to make it easier for current TiddlyWiki users to incorporate into their wikis.
