### ISSUE TITLE
how to show graph view of all tiddlers?

### ISSUE THREAD

**Issue by varvir** [joekroese/tiddlyroam#5]
graph shows only a current tiddler and tiddlers which are associated to current tiddler.

can i see graph of all of tiddlers?

can i filter nodes which have specific degrees?

**Comment by Tom271** [comment]
In the map tab, click on the orange sun/star and change the neighbourhood scope to "No limit". This should let you see the graph of all tiddlers.

![image](https://user-images.githubusercontent.com/7256543/81172462-337e4100-8f96-11ea-9232-d55b532ecb05.png)

See the [TiddlyMap docs](http://tiddlymap.org/#Discovering%20the%20neighbourhood) for more info

**Comment by jokroese** [comment]
@Tom271's method allows you to see all tiddlers that have some finite chain of links to the current tiddler. This deals with most situations.

However, sometimes you may have disconnected subgraphs. In this case, there is not currently an easy way to show all tiddlers at once. In this situation, you can add tiddlers not connected by clicking 'Add Node'.

If you have more questions about the map, I would suggest raising an issue on the plugin I use for generating the map, [TiddlyMap](https://github.com/felixhayashi/TW5-TiddlyMap).
