### ISSUE TITLE
Text Font can not change from black

### ISSUE THREAD

**Issue by washere** [joekroese/tiddlyroam#6]
A light color non-black font is needed for a true dark mode. Coders, writers and other serious writers working for hours generally use thousands of dark modes and themes on various apps. This is a must. Otherwise they are staring into a lightbox or torch most of the day and even at night.

No matter how many:
* Dark Palettes and 
* Dark Themes 
I installed on Tiddlyroam, the text font remains black!

It is being over-ridden by the core. Basically all the dark modes (palettes and themes) for Tiddlyroam are fake dark themes/modes as a result of this.

Can you give us the ability to change the main text font to other colors? And not be stuck for ever with black?

Thanks for the great work.

**Comment by Tom271** [comment]
Are you using TiddlyRoam on desktop? 

If you click the settings icon, then click on the Appearance tab. From there you can select from the preinstalled palettes, which include a few dark modes. If that's not suitable, try following [this guide](https://tiddlywiki.com/static/ColourPalettes.html) to create your own.

**Comment by joekroese** [comment]
'Contrast (Dark)', 'Nord' and 'Twilight' are dark mode palettes with non-black fonts included by default with TiddlyRoam. Does following the process described by @Tom271 to use these work for you @washere?

**Comment by jokroese** [comment]
You're right @washere. The dark mode themes are getting overridden. I'll look into it.

**Comment by jokroese** [comment]
The dark mode was being overridden by some files incorporated from TiddlyBlink. I've removed the parts forcing font colour. TiddlyRoam now has true dark mode.

<img width="726" alt="Screenshot 2020-05-07 at 19 02 53" src="https://user-images.githubusercontent.com/7649772/81323686-0913ad00-9096-11ea-98c0-f9478cc199ef.png">

To use them, follow @Tom271's steps. There are around 5 dark modes that come with TiddlyRoam by default. Thanks for pointing out the issue @washere!
