### ISSUE TITLE
Will TiddlyRoam stay up to date with TiddlyBlink and TiddlyMap?

### ISSUE THREAD

**Issue by plainspace** [joekroese/tiddlyroam#7]

**Comment by Tom271** [comment]
I believe this will be answered by #3

**Comment by jokroese** [comment]
TiddlyWiki still doesn't seem to have a sophisticated dependency manager. The closest you can get to one is dragging your whole html file into https://tiddlywiki.com/upgrade.html and letting it update any plugins. I do this every now and then to incorporate changes from plugins. Of course, this is not ideal but deals with some of the issues.

More complicated is that TiddlyBlink is just a webpage and not (yet) a plugin. I am yet to work out a plan for incorporating it. However, it does not seem to be under regular development so is not currently causing any issues.

Your question taps into a more general question for moving forwards: what does best practice look like for a project like TiddlyRoam? This ad-hoc way of dealing with dependencies is quite alien to normal version control workflows. Also, some of the development requires having the project open, clicking around to make changes and then saving the whole file! It's all quite bizarre and difficult to find a robust workflow.

The conclusion I think is: we should speak to other TiddlyWiki developers to work out some best practices.
