### ISSUE TITLE
Assign color to node in the map, or to the "type" of node

### ISSUE THREAD

**Issue by akelai** [joekroese/tiddlyroam#8]
This tool is fantastic.

Though:

In the map, I want to immediately understand (i.e. visually, that is e.g. by **color**) if a node is of some type that I can define.

For example, let's say I want to distinguish *Person*, *Company*, and... well, say, anything else: then I should have nodes with 3 different colors in a map (if there is at least a person, a company, and something else).

Is this already possible? Otherwise, please consider this as a feature request.

**Comment by Tom271** [comment]
[Does this answer your question?](http://tiddlymap.org/#Styling%20Nodes)

In particular, the Global Group Styles section.

**Comment by akelai** [comment]
Yes! Thank you :)
